version: "3.9"

services:
  deno:
    container_name: deno_hello_world
    image: deno
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "${PORT}:${PORT}"
